"""
Central registry of API error codes, matching docs/api-reference.md.
Using constants instead of raw strings avoids typos causing silent
frontend error-handling mismatches.
"""

AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS"
AUTH_TOKEN_EXPIRED = "AUTH_TOKEN_EXPIRED"
AUTH_TOKEN_INVALID = "AUTH_TOKEN_INVALID"
PERMISSION_DENIED = "PERMISSION_DENIED"
RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"
VALIDATION_ERROR = "VALIDATION_ERROR"
MODEL_UNAVAILABLE = "MODEL_UNAVAILABLE"
DUPLICATE_RESOURCE = "DUPLICATE_RESOURCE"
